board_name = {"01": "door",
              "02": "motion",
              "03": "fire_protect",
              "04": "glass",
              "05": "leaks",
              "06": "mpc",
              "07": "range",
              "08": "combi",
              "09": "fire_protect_plus",
              "10": "key_pad",
              "11": "space",
              "12": "button",
              "13": "motion_cam",
              "14": "motion_plus",
              "15": "door_plus",
              "16": "",
              "17": "transmitter",
              "18": "relay",
              "19": "mpo",
              "20": "street_siren",
              "21": "home_siren_v4",
              "30": "socket",
              "31": "wall_switch",
              "33": "hub"
              }
