# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui',
# licensing of 'main_gui.ui' applies.
#
# Created: Thu May 23 16:54:26 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 676)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.REGISTER = QtWidgets.QPushButton(self.centralwidget)
        self.REGISTER.setGeometry(QtCore.QRect(40, 20, 141, 41))
        self.REGISTER.setCheckable(True)
        self.REGISTER.setObjectName("REGISTER")
        self.ADD_PROG = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_PROG.setGeometry(QtCore.QRect(40, 80, 141, 41))
        self.ADD_PROG.setCheckable(True)
        self.ADD_PROG.setObjectName("ADD_PROG")
        self.ADD_ASSEMBLER = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_ASSEMBLER.setEnabled(True)
        self.ADD_ASSEMBLER.setGeometry(QtCore.QRect(40, 140, 141, 41))
        self.ADD_ASSEMBLER.setCheckable(True)
        self.ADD_ASSEMBLER.setObjectName("ADD_ASSEMBLER")
        self.START = QtWidgets.QPushButton(self.centralwidget)
        self.START.setGeometry(QtCore.QRect(40, 550, 141, 61))
        self.START.setObjectName("START")
        self.DELETE = QtWidgets.QPushButton(self.centralwidget)
        self.DELETE.setGeometry(QtCore.QRect(40, 440, 141, 41))
        self.DELETE.setCheckable(True)
        self.DELETE.setObjectName("DELETE")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 250, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ADD_LONGTEST = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_LONGTEST.setGeometry(QtCore.QRect(40, 200, 141, 41))
        self.ADD_LONGTEST.setCheckable(True)
        self.ADD_LONGTEST.setObjectName("ADD_LONGTEST")
        self.ADD_QC = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_QC.setGeometry(QtCore.QRect(40, 260, 141, 41))
        self.ADD_QC.setCheckable(True)
        self.ADD_QC.setObjectName("ADD_QC")
        self.ADD_PACKER = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_PACKER.setGeometry(QtCore.QRect(40, 380, 141, 41))
        self.ADD_PACKER.setCheckable(True)
        self.ADD_PACKER.setObjectName("ADD_PACKER")
        self.ADD_TESTROOM = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_TESTROOM.setGeometry(QtCore.QRect(40, 320, 141, 41))
        self.ADD_TESTROOM.setCheckable(True)
        self.ADD_TESTROOM.setObjectName("ADD_TESTROOM")
        self.exc_label = QtWidgets.QLabel(self.centralwidget)
        self.exc_label.setGeometry(QtCore.QRect(260, 60, 651, 71))
        self.exc_label.setAutoFillBackground(False)
        self.exc_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.exc_label.setText("")
        self.exc_label.setObjectName("exc_label")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(259, 325, 651, 221))
        self.output_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 0, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(733, 570, 181, 26))
        self.comboBox.setMouseTracking(False)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.port_choose_label = QtWidgets.QLabel(self.centralwidget)
        self.port_choose_label.setGeometry(QtCore.QRect(510, 560, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.port_choose_label.setFont(font)
        self.port_choose_label.setObjectName("port_choose_label")
        self.ADD_CALIB = QtWidgets.QPushButton(self.centralwidget)
        self.ADD_CALIB.setGeometry(QtCore.QRect(40, 500, 141, 41))
        self.ADD_CALIB.setCheckable(True)
        self.ADD_CALIB.setObjectName("ADD_CALIB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "DBclient", None, -1))
        self.REGISTER.setText(QtWidgets.QApplication.translate("MainWindow", "REGISTER", None, -1))
        self.ADD_PROG.setText(QtWidgets.QApplication.translate("MainWindow", "ADD PROG", None, -1))
        self.ADD_ASSEMBLER.setText(QtWidgets.QApplication.translate("MainWindow", "ADD ASSEMBLER", None, -1))
        self.START.setText(QtWidgets.QApplication.translate("MainWindow", "START", None, -1))
        self.DELETE.setText(QtWidgets.QApplication.translate("MainWindow", "DELETE", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "BD OUTPUT", None, -1))
        self.ADD_LONGTEST.setText(QtWidgets.QApplication.translate("MainWindow", "ADD LONGTEST", None, -1))
        self.ADD_QC.setText(QtWidgets.QApplication.translate("MainWindow", "ADD QC", None, -1))
        self.ADD_PACKER.setText(QtWidgets.QApplication.translate("MainWindow", "ADD PACKER", None, -1))
        self.ADD_TESTROOM.setText(QtWidgets.QApplication.translate("MainWindow", "ADD TESTROOM", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Exceptions", None, -1))
        self.port_choose_label.setText(QtWidgets.QApplication.translate("MainWindow", "Выберите порт", None, -1))
        self.ADD_CALIB.setText(QtWidgets.QApplication.translate("MainWindow", "ADD CALIB", None, -1))

